[package]
name = "bevy-c3d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10"
silico-c3d = { path = "../silico-c3d" }
